# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-07 12:11
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import location_field.models.spatial
import mptt.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('location', location_field.models.spatial.LocationField(default=(1.0, 1.0), srid=4326)),
                ('place', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bookkeeping.Cbo')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitcost', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='files/%Y/%m/%d')),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='_Tagulous_InventoryItem_tags',
        ),
        migrations.RemoveField(
            model_name='business',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='debit_account',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entryitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='inventorystock',
            name='item',
        ),
        migrations.DeleteModel(
            name='InventoryVendor',
        ),
        migrations.RemoveField(
            model_name='account',
            name='business',
        ),
        migrations.AddField(
            model_name='account',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='account',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='entries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbo_entries', to='bookkeeping.Entry'),
        ),
        migrations.AddField(
            model_name='account',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='amount_paying',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='bookkeeping.Account'),
        ),
        migrations.AddField(
            model_name='entry',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='debit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='bookkeeping.Account'),
        ),
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='order',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='closing',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='opening',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='EntryItem',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='InventoryStock',
        ),
        migrations.AddField(
            model_name='item',
            name='credit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_items', to='bookkeeping.Account'),
        ),
        migrations.AddField(
            model_name='item',
            name='debit_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_items', to='bookkeeping.Account'),
        ),
        migrations.AddField(
            model_name='item',
            name='debtors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtors', to='bookkeeping.Account'),
        ),
        migrations.AddField(
            model_name='item',
            name='installments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='bookkeeping.Entry'),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_updates', to='bookkeeping.Entry'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='bookkeeping.Entry'),
        ),
        migrations.AddField(
            model_name='account',
            name='cbo',
            field=models.ForeignKey(db_column='cbo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbo_accounts', to='bookkeeping.Cbo'),
        ),
        migrations.AddField(
            model_name='entry',
            name='cbo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.Cbo'),
        ),
        migrations.AddField(
            model_name='entry',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_items', to='bookkeeping.Item'),
        ),
    ]
