# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 09:40
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_auto_20170807_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unitcost',
        )
    ]
