# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_auto_20170811_1136'),
    ]

    operations = [

        migrations.AlterField(
            model_name='entry',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
