# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_auto_20170811_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBOData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_items', to='bookkeeping.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_items', to='bookkeeping.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='bookkeeping.Entry'),
        ),
    ]
