# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_auto_20170831_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbo',
            name='account_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cbo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cbo',
            name='cboName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cbo',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cbo',
            name='first_login',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cbo',
            name='is_active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cbo',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cbo',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cbo',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
