# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 10:26
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_auto_20170831_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbo',
            name='users',
        )
    ]
