# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import location_field.models.spatial
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_auto_20170831_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('location', location_field.models.spatial.LocationField(default=(1.0, 1.0), srid=4326)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('cboName', models.CharField(blank=True, max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=200, unique=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.NullBooleanField()),
                ('dashboardAccess', models.NullBooleanField()),
                ('account_type', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bookkeeping.Enventure')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
