# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0011_auto_20170831_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enventure',
            name='cboName',
        ),
        
    ]
