# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_login',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='cboName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_facebook',
            new_name='first_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_of_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_of_friend_activity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_of_likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post_shares',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='send_newsletter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unread_notifications_count',
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
