# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170831_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identifier',
            new_name='address',
        ),
    ]
