# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_auto_20170831_1026'),
        ('users', '0003_auto_20170831_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cbo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bookkeeping.Cbo'),
        ),
    ]
