# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0011_auto_20170831_1108'),
        ('users', '0004_user_cbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bookkeeping.Enventure'),
        ),
    ]
